# Generated by Django 4.1 on 2022-10-16 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('description', models.TextField()),
                ('min_fish_size', models.FloatField()),
                ('max_fish_size', models.FloatField()),
                ('min_tank_size', models.FloatField()),
                ('max_tank_size', models.FloatField()),
            ],
        ),
    ]
