# Generated by Django 4.1 on 2023-07-02 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='max_fish_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='max_tank_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='min_fish_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='min_tank_size',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.fish')),
            ],
        ),
    ]
